SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

CREATE TABLE `Joueur` (
  `nomJoueur` varchar(16) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `scoreJoueur` int(11) DEFAULT NULL,
  `nombrePartie` int(11) DEFAULT '0'
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

INSERT INTO `Joueur` (`nomJoueur`, `scoreJoueur`, `nombrePartie`) VALUES
('Julien', 10, 3),
('Dylan', 30, 1),
('Emilie', 4, 3),
('Thomas', 1, 2),
('Tintin', 1, 1);

ALTER TABLE `Joueur` ADD PRIMARY KEY (`nomJoueur`);

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
